# Site settings
title: The Grand AI Handbook
description: Your Ultimate AI Knowledge Hub – Handbooks, Research, Roadmaps, and More!
baseurl: ""
url: "https://grandaihandbook.github.io"
github_username: grandaihandbook
repository: grandaihandbook/grandaihandbook.github.io

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Collections
collections:
  handbooks:
    output: true
    permalink: /handbooks/:path/
  research:
    output: true
    permalink: /research/:path/
  roadmaps:
    output: true
    permalink: /roadmaps/:path/
  projects:
    output: true
    permalink: /projects/:path/
  resources:
    output: true
    permalink: /resources/:path/
  ecosystem:
    output: true
    permalink: /ecosystem/:path/
  opportunities:
    output: true
    permalink: /opportunities/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "handbooks"
    values:
      layout: "handbook"
  - scope:
      path: ""
      type: "roadmaps"
    values:
      layout: "roadmap"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .gitignore
  - CONTRIBUTING.md
  - LICENSE
  - README.md
  - CNAME
