# Site settings
title: The Grand AI Handbook
description: Your Ultimate AI Knowledge Hub – Handbooks, Research, Roadmaps, and More!
baseurl: ""
url: "https://grandaihandbook.github.io"
github_username: grandaihandbook
repository: grandaihandbook.github.io

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed # for production

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Collections
collections:
  handbooks:
    output: true
    permalink: /content/handbooks/:path/
  generative-ai:
    output: true
    permalink: /content/handbooks/generative-ai/:path/
  computer-vision:
    output: true
    permalink: /content/handbooks/computer-vision/:path/
  reinforcement-learning:
    output: true
    permalink: /content/handbooks/reinforcement-learning/:path/
  nlp:
    output: true
    permalink: /content/handbooks/nlp/:path/
  explainable-ai:
    output: true
    permalink: /content/handbooks/explainable-ai/:path/
  foundation-models:
    output: true
    permalink: /content/handbooks/foundation-models/:path/
  mlops:
    output: true
    permalink: /content/handbooks/mlops/:path/
  research:
    output: true
    permalink: /content/research/:path/
  weekly-papers:
    output: true
    permalink: /content/research/weekly-papers/:path
  weekly-papers2025:
    output: true
    permalink: /content/research/weekly-papers/2025/:path
  roadmaps:
    output: true
    permalink: /roadmaps/:path/
  projects:
    output: true
    permalink: /projects/:path/
  resources:
    output: true
    permalink: /resources/:path/
  ecosystem:
    output: true
    permalink: /ecosystem/:path/
  opportunities:
    output: true
    permalink: /opportunities/:path/
  content:
    output: true
    permalink: /content/:path/
  about:
    output: true
    permalink: /content/about/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "handbooks"
    values:
      layout: "handbook"
  - scope:
      path: ""
      type: "roadmaps"
    values:
      layout: "roadmap"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: "content"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "about"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .gitignore
  - LICENSE
  - README.md
  - CNAME
